#!/bin/bash

set -e

echo "📋 Deployment Configuration Guide"
echo "================================="
echo ""
echo "Prerequisites:"
echo "  - AWS CLI installed and configured"
echo "  - IAM user with ECR, ECS, and CodeBuild permissions"
echo "  - Docker installed locally"
echo ""
echo "Quick Start - Docker Compose (Local):"
echo "  1. Install Docker Desktop"
echo "  2. Run: docker-compose up -d"
echo "  3. Access frontend: http://localhost"
echo ""
echo "AWS ECS Deployment (Recommended):"
echo "  1. Create ECR repositories:"
echo "     aws ecr create-repository --repository-name al-masrya --region us-east-1"
echo ""
echo "  2. Create ECS cluster:"
echo "     aws ecs create-cluster --cluster-name al-masrya --region us-east-1"
echo ""
echo "  3. Register ECS task definition:"
echo "     aws ecs register-task-definition --cli-input-json file://ecs-task-definition.json"
echo ""
echo "  4. Create ECS service:"
echo "     aws ecs create-service \\"
echo "       --cluster al-masrya \\"
echo "       --service-name al-masrya-service \\"
echo "       --task-definition al-masrya-task:1 \\"
echo "       --desired-count 2 \\"
echo "       --launch-type FARGATE \\"
echo "       --network-configuration 'awsvpcConfiguration={subnets=[subnet-xxx],securityGroups=[sg-xxx],assignPublicIp=ENABLED}'"
echo ""
echo "AWS Elastic Beanstalk Deployment (Easiest):"
echo "  1. Initialize Elastic Beanstalk:"
echo "     eb init -p 'Node.js 18 running on 64bit Amazon Linux 2' al-masrya"
echo ""
echo "  2. Deploy:"
echo "     eb create al-masrya-env"
echo "     eb deploy"
echo ""
echo "AWS Lambda + API Gateway (Serverless):"
echo "  1. Bundle frontend as static S3 content"
echo "  2. Deploy microservices as Lambda containers"
echo "  3. Use API Gateway for routing"
echo ""
echo "Environment Variables to set:"
echo "  - MONGO_URI: MongoDB connection string"
echo "  - NODE_ENV: production"
echo "  - JWT_SECRET: Your secret key"
echo ""
echo "Monitoring:"
echo "  - CloudWatch Logs: /ecs/al-masrya"
echo "  - CloudWatch Alarms: Set up for CPU, Memory, and Error rates"
echo ""
echo "For questions, visit: https://github.com/Youssefwael2023/NestJs-E-commerce-Project"
